site_name: 'Windmill MkDocs Theme'
site_description: 'MkDocs theme focused on navigation and usability.'
site_author: 'Dmitry S'

repo_url: https://github.com/gristlabs/mkdocs-windmill

theme:
  name: null
  custom_dir: mkdocs_windmill
  # Copy settings from mkdocs_theme.yml, which is ignored by custom_dir themes.
  static_templates: [404.html]
  search_index_only: true
  include_search_page: true

pages:
- Windmill Theme:
  - Usage: index.md
  - Customization: customization.md
- Samples:
  - Sample Page A: sample-a.md
  - Sample Subfolder:
    - Sample Subpage A1: sample-a1.md
    - Sample Subpage A2: sample-a2.md
  - Sample Page B: sample-b.md

markdown_extensions:
  - toc:
      permalink: '#'

extra:
  history_buttons: false
  version: 0.1.5
